backend:
  name: git-gateway
  branch: preview  # pokud máš větev "master", změň na "master"

media_folder: "admin"
public_folder: "/admin"

collections:
  - name: "pages"
    label: "Stránky"
    files:
      - label: "Hlavní stránka"
        name: "index"
        file: "index.html"
        fields:
          - { label: "Titulek", name: "title", widget: "string" }
          - { label: "Popis", name: "description", widget: "text" }
